
local globals = {
	ENERGY_TIME_PERIOD = 1,
	STRESS_AVE_TIME = 15,
	VIEW_SPEED_LIMIT = 150,
	CONTACT_FORCE = 0,
	FORCE_STORE = 1,
	
	SEA_DEATH = 950,
	
	SCORE_DISPLAY_TURN = 4,
	
	CONSOLE_BOTTOM = 700,
	
	DENSITY_MULT = 0.75,
	SPEED_LIMIT = 850,
	YEET = false,
	
	LINK_DRAW_ORDER = 10,
	PIECE_DRAW_ORDER = 4,
	PIECE_DRAW_ORDER_SHOP = 20,
	WORLD_MOUSE_DRAW_ORDER = 25,
	EFFECT_DRAW_ORDER = 22,
}

return globals