
local globals = {
	ENERGY_TIME_PERIOD = 1,
	STRESS_AVE_TIME = 30,
	VIEW_SPEED_LIMIT = 150,
	CONTACT_FORCE = 0,
	FORCE_STORE = 1,
	
	SPEED_LIMIT = 850,
	
	LINK_DRAW_ORDER = 10,
	PIECE_DRAW_ORDER = 4,
	PIECE_DRAW_ORDER_SHOP = 20,
	WORLD_MOUSE_DRAW_ORDER = 25,
}

return globals