return {
	{
		name = "interface",
		file = "resources/images/interface/interface_slant.png",
		form = "image",
		xScale = 0.21,
		yScale = 0.21,
		xOffset = 2100/3200,
		yOffset = 327/400,
	},
	{
		name = "interface_right",
		file = "resources/images/interface/interface_slant.png",
		form = "image",
		xScale = 0.21,
		yScale = 0.21,
		xOffset = 900/3200,
		yOffset = 74/400,
	},
	{
		name = "interface_flip",
		file = "resources/images/interface/interface_flip.png",
		form = "image",
		xScale = 0.21,
		yScale = 0.21,
		xOffset = 1550/3200,
		yOffset = 74/400,
	},
	{
		name = "interface_flip_big",
		file = "resources/images/interface/interface_flip.png",
		form = "image",
		xScale = 0.21,
		yScale = 0.21,
		xOffset = 720/3200,
		yOffset = 74/400,
	},
	{
		name = "interface_rot",
		file = "resources/images/interface/interface_rot.png",
		form = "image",
		xScale = 0.21,
		yScale = 0.21,
		xOffset = 50/400,
		yOffset = 0.5,
	},
	{
		name = "popup",
		file = "resources/images/interface/popup.png",
		form = "image",
		xScale = 0.8,
		yScale = 0.8,
		xOffset = 0.5,
		yOffset = 0.5,
	},
}

