return {
	{
		name = "science_icon",
		file = "resources/images/interface/science.png",
		form = "image",
		xScale = 0.45,
		yScale = 0.45,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "energy_icon",
		file = "resources/images/interface/energy.png",
		form = "image",
		xScale = 0.45,
		yScale = 0.45,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "demand_icon",
		file = "resources/images/interface/demand.png",
		form = "image",
		xScale = 0.45,
		yScale = 0.45,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "admin_icon",
		file = "resources/images/interface/admin.png",
		form = "image",
		xScale = 0.45,
		yScale = 0.45,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "sea_icon",
		file = "resources/images/interface/hating_the_planet.png",
		form = "image",
		xScale = 0.45,
		yScale = 0.45,
		xOffset = 0.5,
		yOffset = 0.5,
	},
	{
		name = "bank_icon",
		file = "resources/images/interface/stonksbad.png",
		form = "image",
		xScale = 0.45,
		yScale = 0.45,
		xOffset = 0.5,
		yOffset = 0.5,
	},
}

